{% set name = "fresnel" %}
{% set version = "0.13.2" %}
{% set sha256 = "4e213e62fd48a4f8e12d048f952fea5cbca1453cf6a941a34797fcc73ada95e6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # fn: {{ name }}-{{ version }}.tar.gz
  # url: https://github.com/glotzerlab/{{ name }}/releases/download/v{{ version }}/{{ name }}-v{{ version }}.tar.gz
  # sha256: {{ sha256 }}
  git_url: https://github.com/glotzerlab/fresnel
  git_rev: master

build:
  number: 0
  # the dependencies require visual studio 13+
  skip: true  # [win and vc<13]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - cmake
    - ninja

  host:
    - python
    - numpy
    - embree3
    - tbb
    - tbb-devel
    - pybind11
    - qhull ==2020.2

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - embree3
    - tbb
    - pillow
    - qhull ==2020.2

test:
  requires:
    - pytest
  imports:
    - fresnel
  source_files:
    - setup.cfg
  commands:
    - cd /
    - pytest --pyargs fresnel -v -ra

about:
  home: https://github.com/glotzerlab/{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Path tracing for soft matter simulations.

  description: |
    Fresnel is a python library that path traces publication quality images of soft matter simulations in real time.
  doc_url: https://{{ name }}.readthedocs.io
  dev_url: https://github.com/glotzerlab/{{ name }}

extra:
  recipe-maintainers:
    - joaander
    - bdice
