{% set name = "fresnel" %}
{% set version = "0.7.1" %}
{% set sha256 = "08e0ba0254f3108a7145d86a18ae126613a29cf3a2551f330e38f6b2f6e29482" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://glotzerlab.engin.umich.edu/Downloads/{{ name }}/{{ name }}-v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  # the upstream package does not support windows
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake

  host:
    - python
    - numpy
    - embree3
    - tbb
    - tbb-devel

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - embree3
    - tbb
    - pillow

test:
  requires:
    - pytest
  imports:
    - fresnel
  source_files:
    - test/
    - setup.cfg
  commands:
    - cd test && pytest

about:
  home: https://github.com/glotzerlab/{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Path tracing for soft matter simulations.'

  description: |
    Fresnel is a python library that path traces publication quality images of soft matter simulations in real time.
  doc_url: https://{{ name }}.readthedocs.io
  dev_url: https://github.com/glotzerlab/{{ name }}

extra:
  recipe-maintainers:
    - joaander
    - bdice
