{% set name = "fresnel" %}
{% set version = "0.6.0" %}
{% set sha256 = "de1b18f87b5bcdd96844c143d6a9cf560df873a9f1f7eae8d6ff2eac5a1d2467" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://glotzerlab.engin.umich.edu/Downloads/{{ name }}/{{ name }}-v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  # the upstream package does not support windows
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake

  host:
    - python
    - numpy
    - embree3
    - tbb

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - embree3
    - tbb
    - pillow

test:
  requires:
    - pytest
  imports:
    - fresnel
  source_files:
    - test/
    - setup.cfg
  commands:
    - cd test && pytest

about:
  home: https://bitbucket.org/glotzer/{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Path tracing for soft matter simulations.'

  description: |
    Fresnel is a python library that path traces publication quality images of soft matter simulations in real time.
  doc_url: https://bitbucket.org/glotzer/{{ name }}
  dev_url: https://bitbucket.org/glotzer/{{ name }}

extra:
  recipe-maintainers:
    - joaander
