{% set name = "fresnel" %}
{% set version = "0.10.1" %}
{% set sha256 = "2ba1f85f3599f349a7a20d5dcc19a84ea43bb8dd707cad22bbf9f4767ca4b955" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://glotzerlab.engin.umich.edu/Downloads/{{ name }}/{{ name }}-v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  # the upstream package does not support windows or python2.7
  skip: true  # [win]
  skip: true  # [py27]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake

  host:
    - python
    - numpy
    - embree3
    - tbb
    - tbb-devel
    - pybind11
    - qhull

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - embree3
    - tbb
    - pillow
    - qhull

test:
  requires:
    - pytest
  imports:
    - fresnel
  source_files:
    - test/
    - setup.cfg
  commands:
    - cd test && pytest

about:
  home: https://github.com/glotzerlab/{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Path tracing for soft matter simulations.'

  description: |
    Fresnel is a python library that path traces publication quality images of soft matter simulations in real time.
  doc_url: https://{{ name }}.readthedocs.io
  dev_url: https://github.com/glotzerlab/{{ name }}

extra:
  recipe-maintainers:
    - joaander
    - bdice
