{% set name = "fresnel" %}
{% set version = "0.13.1" %}
{% set sha256 = "45b43392d7d0af06aec53182df7c818a633675823c9f808b93d0ac513aa2413f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/glotzerlab/{{ name }}/releases/download/v{{ version }}/{{ name }}-v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - rpath.patch

build:
  number: 0
  # the upstream package does not support windows or python2.7
  skip: true  # [win or py<36]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake

  host:
    - python
    - numpy
    - embree3
    - tbb
    - tbb-devel
    - pybind11
    - qhull ==2020.2

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - embree3
    - tbb
    - pillow
    - qhull ==2020.2

test:
  requires:
    - pytest
  imports:
    - fresnel
  source_files:
    - setup.cfg
  commands:
    - cd /
    - pytest --pyargs fresnel -v -ra

about:
  home: https://github.com/glotzerlab/{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Path tracing for soft matter simulations.

  description: |
    Fresnel is a python library that path traces publication quality images of soft matter simulations in real time.
  doc_url: https://{{ name }}.readthedocs.io
  dev_url: https://github.com/glotzerlab/{{ name }}

extra:
  recipe-maintainers:
    - joaander
    - bdice
