appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: YdludzH2zECm2MRkWZsl+dfU1RjiY0qqWv6B9kCEXbte99MEUdgQG3d3lDBkMriqbzxZTky1coO53HDAZ2ZZg+3y3nF57RHgv4G/9jIVaXyPzBlDag0Xo3V4ntDUogtfdWTHZca3qTTiYI+F2jbtP4R+odHxtG19sRUT6HPKq5VK9JSWJ+V5w2+XJQn37vkvjcyl6OHGWO06mDjo3eZbK5Aa0f8JFccZ4S9QNHn3pZL3IUDYbOKPvt0ABGZsikQXy3Uyz/a15aurQK2CwuX/t6tnWhfDBpeCMFxNqyS13hhRq71bN6hP2ZJeM/vjvVW9qvcryK08AJkiER+XnbbX1za6K1hmgHGDeag0cOe0tZCSQNFYiiq3tbtH02EKKT7/52ZDAnCx0KyKXcvIHwTr35UgKf+BslsZ3ySkJ41z6KJw5Q/EqrpYc87h7WszQXQ3WfhFbxTvqOHrCZNed5b+EmxGXIsIuTbYNTGm153IJzIR7TBGR9XLTz2IXaIBO/vFmPgYfycri9gTQp74TeckzMess6OU8ZUZnVOYfQx54y/c2TouUCbqpALetz765KE5YcpjwH+97pUm7ocE84TkXy/zXMoe66TFQKgBYWm8oQHQP4cqhq2VuF6Ma6/UhglIPr8mHHOECZFhwJM0J9nk8NooZZf/cTrplTl+voYC0Rc=}
conda_forge_output_validation: true
