travis:
  secure:
    BINSTAR_TOKEN: ATXXqyMalWH6Muc9XqOxJqB0ntRad+RyliRd1Xtu9gEkV2hYX1+KM4eX9jxNJmPcgeZy+IGY1NCcNs9fcmOaFl8P6o72DzG+4l5ZqCGxLg6f6KxGesPku8XP7EnKQB2j3BXuGS6yVLkrOUn5EtcbpB6u4k8PlTMV3VnNBm2NzE1uFv+Yxe7gr5SLiyPbBGo4cPDP841OsQWk4SbJHzdmqUA1dcWW3s2LwlEjkRA+141VtCtUB/dhGF96h/JBs9GJ64WYUSVo3J7MkPz14tE66MZsnlA0lwHYjbItI1p+nImkIKJiDImuVeWJOYVeZ64wd37tfYCmJl6l1Jq0pB0bpcPnR7sMChog2qtoMvcOPAOxPQtnVI9JowfEChnrnyoZbyHsXJlvsEMhOcIrJguGMMO9Yif0vXW7snX+zPHzv5JVRyxQfrP+tWqo95zAZaFidbsfE+SSbyGk5clA0fwFn9cme0cjeXCg+GgAK8/2XHtND7vATwMPu/N53I2zwE6ZxwAg7Ztnl+UB+G5SgVkwBYR75NV9TM39Lpvy6mX1BC9ep25/+Eqex9eH8n7yqijSrWET2/0WqLhXcsSrZPUpc4T9I2Mv6VHq0eshpno8ixawc9NnhYeWYboAQ8sZrrfdGY0ve4qv99pRg97tUXBuvFz+X+1lfmd2X5cXXX7xIn4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
